config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
    path_names: {
      sign_in: 'sign-in',
    }
  namespace :admins do
    resources :asanas, except: [:show, :destroy]
  end
  resources :home, only: [:index]
  get '/asanas/by/:search_type', to: 'asanas#index', as: :asanas_by_search_default
  get '/asanas/by/:search_type/:search', to: 'asanas#index', as: :asanas_by_search
  resources :asanas, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asana.rb
class Asana < ApplicationRecord
  extend FriendlyId
  friendly_id :sanskrit_name, use: :slugged
  include AttrJson::Record
  include AttrJson::Record::QueryScopes
  include AttrJson::NestedAttributes

  attr_json :chakras, AsanaChakra.to_type, array: true
  attr_json :benefits, AsanaBenefit.to_type, array: true
  attr_json :body_parts, AsanaBodyPart.to_type, array: true
  attr_json :restrictions, AsanaRestriction.to_type, array: true
  attr_json :effects, AsanaEffect.to_type, array: true
  attr_json_accepts_nested_attributes_for :chakras, :benefits, :body_parts, :restrictions, :effects

  Chakras = ["Muladhara", "Svadhisthana", "Manipura", "Anahata", "Visuddha", "Ajna", "Sahasrara" ]
  Benefits = ["Better flexibility", "Better posture", "Muscle strength", "Tones the body", "Better sleep", "More energy", "Stronger Bones.", "Improves digestion"]
  BodyParts = ["Head", "Neck", "Shoulder", "Arms", "Chest", "Breast", "Waist", "Belly", "Abdomen", "Hip", "Pelvis", "Liver", "Uterus", "Pancreas", "Thigh", "Knee"]
  Restrictions = ["Children under age of 12","During menstruation", "During pregnancy"]
end

app/models/asana_benefit.rb
class AsanaBenefit
  include AttrJson::Model
  include AttrJson::Model::CocoonCompat
  attr_json :name, :string


  # validates :name, presence: true

end

app/models/asana_body_part.rb
class AsanaBodyPart
  include AttrJson::Model
  include AttrJson::Model::CocoonCompat
  attr_json :name, :string

  # validates :name, presence: true

end

app/models/asana_chakra.rb
class AsanaChakra
  include AttrJson::Model
  include AttrJson::Model::CocoonCompat
  attr_json :name, :string

  # validates :name, presence: true

end

app/models/asana_effect.rb
class AsanaEffect
  include AttrJson::Model
  include AttrJson::Model::CocoonCompat
  attr_json :name, :string


  # validates :name, presence: true

end

app/models/asana_restriction.rb
class AsanaRestriction
  include AttrJson::Model
  include AttrJson::Model::CocoonCompat
  attr_json :name, :string

  # validates :name, presence: true

end

app/controllers/admins/asanas_controller.rb
class Admins::AsanasController <  Admins::BaseController

  before_action :find_asana, only: [:edit, :update]

  def new
    @asana = Asana.new
    if Rails.env.development?
      @asana = FactoryBot.build(:asana)
    end
  end

  def create
    @asana = Asana.new(asana_params)
    if @asana.save
      flash_created
      redirect_to edit_admins_asana_path(@asana)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @asana.update_attributes(asana_params)
      flash_updated
      redirect_to edit_admins_asana_path(@asana)
    else
      render 'edit'
    end
  end

  def index
    @asanas = Asana.all.order(asana_order: :asc)
  end

  private

  def asana_params
    params.require(:asana).permit(:sanskrit_name, :name, :asana_order, :introduction, :technique, :variation, :concentration, :afterward,  chakras_attributes: [:id, :name, :_destroy], benefits_attributes: [:id, :name, :_destroy], body_parts_attributes: [:id, :name, :_destroy], restrictions_attributes: [:id, :name, :_destroy], effects_attributes: [:id, :name, :_destroy])
  end

  def find_asana
    @asana = Asana.friendly.find(params[:id])
  end

end

app/controllers/admins/base_controller.rb
class Admins::BaseController < ApplicationController

  before_action :authenticate_admin!

  def flash_created
    flash.notice = "Created Successfully."
  end

  def flash_updated
    flash.notice = "Updated Successfully."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/asanas_controller.rb
class AsanasController < ApplicationController
  def index
    if params[:search_type].present?
      case params[:search_type].downcase
      when 'chakras'
        params[:search] = "Muladhara" unless params[:search].present?
        search = params[:search].gsub('-', ' ').capitalize
        @asanas = Asana.jsonb_contains("chakras.name" => search).order(asana_order: :asc)
      when 'benefits'
        params[:search] = "Better flexibility"  unless params[:search].present?
        search = params[:search].gsub('-', ' ').capitalize
        @asanas = Asana.jsonb_contains("benefits.name" => search).order(asana_order: :asc)
      when 'body-parts'
        params[:search] = "Head" unless params[:search].present?
        search = params[:search].gsub('-', ' ').capitalize
        @asanas = Asana.jsonb_contains("body_parts.name" => search).order(asana_order: :asc)
      when 'restrictions'
        params[:search] = "Children under age of 12"  unless params[:search].present?
        search = params[:search].gsub('-', ' ').capitalize
        @asanas = Asana.jsonb_contains("restrictions.name" => search).order(asana_order: :asc)
      end
    else
      @asanas = Asana.all.order(asana_order: :asc)
    end
  end

  def show
    @asana = Asana.friendly.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/admins/asanas_helper.rb
module Admins::AsanasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asanas_helper.rb
module AsanasHelper
end

app/helpers/form_helper.rb
module FormHelper
  def form_error_messages(form_errors)
    return "" if form_errors.empty?
    messages = []
    form_errors.messages.each do |field, errors|
      errors.each do |error|
        if field == :base
          messages << content_tag(:p, "<strong>#{error}</strong>.".html_safe)
        else
          messages << content_tag(:p, "<strong>#{field.to_s.titleize}</strong> #{error}.".html_safe)
        end
      end
    end
    # CHANGE ME
    html = <<-HTML
    <div class='row'>
      <div class='col s12'>
        <div id="error_explanation" class="card yellow lighten-5">
          <div class="card-content pad-25">
            <span class="strong card-title">⚠️ Found #{pluralize(form_errors.count, 'error')}:</span>
            <div class="error_messages">
              <blockquote>
                #{messages.join}
              </blockquote>
            </div>
          </div>
        </div>
      </div>
    </div>
    HTML

    html.html_safe
  end

end

app/views/admins/asanas/_benefit_fields.html.haml
.nested-fields.mt-3
  = f.label "Select a benefit"
  = f.input_field :name, collection: Asana::Benefits
  %br
  %br
  = link_to_remove_association "Remove benefit", f, class: "btn btn-outline-danger btn-sm"

app/views/admins/asanas/_body_part_fields.html.haml
.nested-fields
  = f.label "Body Parts"
  = f.input_field :name, collection: Asana::BodyParts
  %br
  %br
  = link_to_remove_association "Remove body part", f, class: "btn btn-outline-danger btn-sm"

app/views/admins/asanas/_chakra_fields.html.haml
.nested-fields.mt-3
  = f.label "Select a chakra"
  = f.input_field :name, collection: Asana::Chakras
  %br
  %br
  = link_to_remove_association "Remove chakra", f, class: "btn btn-outline-danger btn-sm"

app/views/admins/asanas/_effect_fields.html.haml
.nested-fields
  .form-group
    = f.label :name
    = f.input_field :name, class: "form-control"
  %br
  %br
  = link_to_remove_association "Remove effect", f, class: "btn btn-outline-danger btn-sm"

app/views/admins/asanas/_form.html.haml
= simple_form_for @asana, url: @asana.new_record? ? admins_asanas_path : admins_asana_path(@asana) do |f|
  = f.error_notification

  .form-group
    = f.label :sanskrit_name
    = f.input_field :sanskrit_name, required: true, class: "form-control"
  .form-row
    .col-9
      = f.label :name
      = f.input_field :name, required: true, class: "form-control"
    .col
      = f.label :asana_order, "Order"
      = f.input_field :asana_order, required: true, class: "form-control"
  .form-group
    = f.label :introduction
    = f.input_field :introduction, class: "form-control", rows:5
  .form-group
    = f.label :technique
    = f.input_field :technique, class: "form-control", rows:5
  .form-group
    = f.label :variation
    = f.input_field :variation, class: "form-control", rows:5
  .form-group
    = f.label :concentration
    = f.input_field :concentration, class: "form-control", rows:5
  .form-group
    = f.label :afterward
    = f.input_field :afterward, class: "form-control", rows:5


  .row
    .col.col-sm-12.col-md-6
      .card.border-secondary.mb-3
        %h5.card-header Chakras
        .card-body.text-dark
          #chakras
            %ul.list-group.list-group-flush
              = f.simple_fields_for :chakras do |chakra|
                %li.list-group-item
                  = render 'chakra_fields', f: chakra
              .links.mt-5
                = link_to_add_association 'Add chakra', f, :chakras, class: "btn btn-secondary"

    .col.col-sm-12.col-md-6
      .card.border-secondary.mb-3
        %h5.card-header Benefits
        .card-body.text-dark
          #benefits
            %ul.list-group.list-group-flush
              = f.simple_fields_for :benefits do |benefit|
                %li.list-group-item
                  = render 'benefit_fields', f: benefit

              .links.mt-5
                = link_to_add_association 'Add benefit', f, :benefits, class: "btn btn-secondary"

    .col.col-sm-12.col-md-6
      .card.border-secondary.mb-3
        %h5.card-header Body parts
        .card-body.text-dark
          #body_parts
            %ul.list-group.list-group-flush
              = f.simple_fields_for :body_parts do |body_part|
                %li.list-group-item
                  = render 'body_part_fields', f: body_part
            .links.mt-5
              = link_to_add_association 'Add body part', f, :body_parts, class: "btn btn-secondary"

    .col.col-sm-12.col-md-6
      .card.border-secondary.mb-3
        %h5.card-header Restrictions
        .card-body.text-dark
          #restrictions
            %ul.list-group.list-group-flush
              = f.simple_fields_for :restrictions do |restriction|
                %li.list-group-item
                  = render 'restriction_fields', f: restriction
              .links.mt-5
                = link_to_add_association 'Add restriction', f, :restrictions, class: "btn btn-secondary"


    .col.col-sm-12.col-md-6
      .card.border-secondary.mb-3
        %h5.card-header Effects
        .card-body.text-dark
          #effects
            %ul.list-group.list-group-flush
              = f.simple_fields_for :effects do |effect|
                %li.list-group-item
                  = render 'effect_fields', f: effect
              .links.mt-5
                = link_to_add_association 'Add effect', f, :effects, class: "btn btn-secondary"

  = f.button :submit, class: "btn btn-primary btn-lg btn-block"

app/views/admins/asanas/_restriction_fields.html.haml
.nested-fields
  = f.input :name, collection: Asana::Restrictions
  = link_to_remove_association "Remove restriction", f

app/views/admins/asanas/edit.html.haml
.container.mt-5
  %h5
    = link_to admins_asanas_path do
      %i.fas.fa-arrow-circle-left
      Asanas
  %h1 Edit #{@asana.sanskrit_name}
  = render 'form'

app/views/admins/asanas/index.html.haml
.container.mt-5
  %h1 Asanas

  = link_to "New asana", new_admins_asana_path, class: "btn btn-primary "
  %br
  %br

  %table.table.table-striped
    %thead
      %tr
        %th{:scope => "col"} Sanskrit Name
        %th{:scope => "col"} Order
        %th{:scope => "col"}
        %th{:scope => "col"}
    %tbody
      - @asanas.each do |asana|
        %tr
          %td= link_to asana.sanskrit_name, edit_admins_asana_path(asana)
          %td= asana.asana_order
          %td= link_to "Edit", edit_admins_asana_path(asana)
          %td= link_to "View", asana_path(asana), target:"_blank"



  / %table
  /   %tr
  /     %th{style: "border: 1px solid black;"} Sanskrit Name
  /     %th{style: "border: 1px solid black;"} Order
  /     %th
  /   - @asanas.each do |asana|
  /     %tr
  /       %td{style: "border: 1px solid black;"}= asana.sanskrit_name
  /       %td{style: "border: 1px solid black;"}= asana.asana_order
  /       %td{style: "border: 1px solid black;"}= link_to "Edit", edit_admins_asana_path(asana)

app/views/admins/asanas/new.html.haml
%h1 New Asana
= render 'form'

app/views/asanas/index.html.haml
.bg-image-container.banner
  .container
    %h1
      ASANAS
      %small (Postures)

    %h5 Essential ways for us to subtly attune, or create a resonance with, a complex range of macrocosmic energies.

%ul.nav.justify-content-center.primary-nav
  %li.nav-item
    =  link_to "All asanas", asanas_path, class: "nav-link"
  %li.nav-item
    =  link_to "By chakras", asanas_by_search_default_path('chakras'), class: "nav-link"
  %li.nav-item
    =  link_to "By benefits", asanas_by_search_default_path('benefits'), class: "nav-link"
  %li.nav-item
    =  link_to "By body parts", asanas_by_search_default_path('body-parts'), class: "nav-link"
  / %li.nav-item
  /   =  link_to "By restrictions", asanas_by_search_default_path('restrictions'), class:"nav-link"

%ul.nav.justify-content-center.secondary-nav
  - if params[:search_type].present?
    -if params[:search_type] == "chakras"
      %li.nav-item
        =  link_to "Muladhara", asanas_by_search_path('chakras', 'muladhara'), class: "nav-link badge badge-light"
      %li.nav-item
        =  link_to "Svadhisthana", asanas_by_search_path('chakras', 'svadhisthana'), class: "nav-link badge badge-light"
      %li.nav-item
        =  link_to "Manipura", asanas_by_search_path('chakras', 'manipura'), class: "nav-link badge badge-light"
      %li.nav-item
        =  link_to "Anahata", asanas_by_search_path('chakras', 'anahata'), class: "nav-link badge badge-light"
      %li.nav-item
        =  link_to "Visuddha", asanas_by_search_path('chakras', 'visuddha'), class: "nav-link badge badge-light"
      %li.nav-item
        =  link_to "Ajna", asanas_by_search_path('chakras', 'ajna'), class: "nav-link badge badge-light"
      %li.nav-item
        =  link_to "Sahasrara", asanas_by_search_path('chakras', 'sahasrara'), class: "nav-link badge badge-light"

  - if params[:search_type].present?
    -if params[:search_type] == "benefits"
      %li.nav-item
        =  link_to "Better flexibility" , asanas_by_search_path('benefits', "better-flexibility"), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Better posture" , asanas_by_search_path('benefits', "better-posture"), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Muscle strength" , asanas_by_search_path('benefits', "muscle-strength"), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Tones the body" , asanas_by_search_path('benefits', 'tones-the-body'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Better sleep" , asanas_by_search_path('benefits', 'better-sleep'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "More energy", asanas_by_search_path('benefits', 'more-energy'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Stronger bones", asanas_by_search_path('benefits', 'stronger-bones'), class: "nav-link badge badge-light "

  - if params[:search_type].present?
    -if params[:search_type] == "body-parts"
      %li.nav-item
        =  link_to "Head", asanas_by_search_path('body-parts', 'head'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Neck ", asanas_by_search_path('body-parts', 'neck'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Shoulders", asanas_by_search_path('body-parts', 'shoulders'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Arms", asanas_by_search_path('body-parts', 'arms'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Chest" , asanas_by_search_path('body-parts', 'chest'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Breast" , asanas_by_search_path('body-parts', 'breast'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Waist" , asanas_by_search_path('body-parts', 'waist'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Belly" , asanas_by_search_path('body-parts', 'belly'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Abdomen" , asanas_by_search_path('body-parts', 'abdomen'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Hip" , asanas_by_search_path('body-parts', 'hip'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Pelvis" , asanas_by_search_path('body-parts', 'pelvis'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Liver" , asanas_by_search_path('body-parts', 'liver'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Uterus" , asanas_by_search_path('body-parts', 'uterus'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Pancreas" , asanas_by_search_path('body-parts', 'pancreas'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Thigh", asanas_by_search_path('body-parts', 'thigh'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "Knee  ", asanas_by_search_path('body-parts', 'knee'), class: "nav-link badge badge-light "

  - if params[:search_type].present?
    -if params[:search_type] == "restrictions"
      %li.nav-item
        =  link_to "Children under age of 12" , asanas_by_search_path('restrictions', 'children-under-age-12'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "During menstruation", asanas_by_search_path('restrictions', 'during-menstruation'), class: "nav-link badge badge-light "
      %li.nav-item
        =  link_to "During pregnancy", asanas_by_search_path('restrictions', 'during-pregnancy'), class: "nav-link badge badge-light "

.container.mt-5
  .row.card-deck
    - @asanas.each do |asana|
      .col-12.col-md-6.col-lg-4.mt-4
        .card.asanas
          .card-body
            .media
              / %i.align-self-center.mr-4.fas.fa-child.fa-4x
              = link_to asana_path(asana) do
                .media-body
                  %h5.mt-0= asana.sanskrit_name
                  %ul
                    - if asana.chakras.present?
                      %li.text-muted= asana.chakras.map(&:name).first(3).join(", ")
                    - if asana.benefits.present?
                      %li.text-muted= asana.benefits.map(&:name).first(3).join(", ")
                    - if asana.body_parts.present?
                      %li.text-muted= asana.body_parts.map(&:name).first(3).join(", ")
                  = link_to "View more", asana_path(asana)

app/views/asanas/show.html.haml
.container.mt-5
  %h5
    = link_to asanas_path do
      %i.fas.fa-arrow-circle-left
      Asanas

  %h1.mt-4
    = @asana.sanskrit_name
  %h5.text-thin= @asana.name

  .row
    .col-sm-12.col-md-12.col-lg-8
      - if @asana.introduction.present?
        = simple_format(@asana.introduction, class: "mt-4")

      %h4.mt-4.mb-3 Technique
      %ul
        = simple_format(@asana.technique,{class: "techniques"}, wrapper_tag: "li")

      - if @asana.variation.present?
        %h6.mt-4
          %strong Variation
        = simple_format(@asana.variation,{class: "techniques mb-4"}, wrapper_tag: "li")

    .col-sm-12.col-md-12.col-lg-4
      .card.bg-light.mb-3
        .card-body
          %h4.card-title Concentration
          %p.card-text= simple_format(@asana.concentration)

      .card.bg-light.mb-3
        .card-body
          %h4.card-title Afterward
          %p.card-text= simple_format(@asana.afterward)

      - if @asana.restrictions.present?
        .card.border-danger.mb-3
          .card-body.text-danger
            %h4.card-title.text-danger Caution
            - @asana.restrictions.each do |restriction|
              %li.card-text= restriction.name

    - if @asana.effects.present?
      .col-sm-12.col-md-12.col-lg-8.order-last
        %h4.mt-4.mb-3 Effects and Benefits
        %ul
          - @asana.effects.each do |effect|
            %li= effect.name

app/views/home/index.html.haml
%h2 Asanas
%h3=  link_to "By benefits", asanas_path
%h3=  link_to "By chakras", asanas_path
%h3=  link_to "By body parts", asanas_path
%h3=  link_to "By restrictions", asanas_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0, minimum-scale=1.0"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.0.13/css/solid.css", :integrity => "sha384-Rw5qeepMFvJVEZdSo1nDQD5B6wX0m7c5Z/pLNvjkB14W6Yki1hKbSEQaX9ffUbWe", :rel => "stylesheet"}/
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.0.13/css/fontawesome.css", :integrity => "sha384-GVa9GOgVQgOk+TNYXu7S/InPTfSDTtBalSgkgqQ7sCik56N9ztlkoTr2f/T44oKV", :rel => "stylesheet"}/

    %title Yoga
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield